### PR TITLE
feat(dep-check): add migration message

### PR DESCRIPTION
**Pull request by tido64**
### Description

Tell users to migrate to `@rnx-kit/align-deps`.

### Test plan

```
cd packages/dep-check
yarn build --dependencies
```

### CODE REVIEW

**Review by afoxman — APPROVED** [review]
What are your plans for the dep-check package going forward?

**Comment by tido64** [comment]
> What are your plans for the dep-check package going forward?

I'm thinking we should remove it and add a notice on npm that this package has been deprecated. I will check on usage numbers some time next month (or after new years) before proceeding. We can probably already add the deprecation notice after this change has been published. What are your thoughts?

**Comment by afoxman** [comment]
> > What are your plans for the dep-check package going forward?
> 
> I'm thinking we should remove it and add a notice on npm that this package has been deprecated. I will check on usage numbers some time next month (or after new years) before proceeding. We can probably already add the deprecation notice after this change has been published. What are your thoughts?

This makes sense. 

People will start seeing this warning message when they run it, and soon after, when you mark is deprecated on npm, they'll see warnings when they install it too. 

After that, I think you can delete the package from the repo. We won't service it anymore. `align-deps` was done very carefully so that it can support migrating users easily. I don't think we should try to continue maintaining `dep-check` at all. People can always stay on the last working copy of it until they are ready to upgrade.

Great work!

**Comment by afoxman** [comment]
> After that, I think you can delete the package from the repo. We won't service it anymore. `align-deps` was done very carefully so that it can support migrating users easily. I don't think we should try to continue maintaining `dep-check` at all. People can always stay on the last working copy of it until they are ready to upgrade.

This may be too aggressive, actually. There are links out there which point to the `dep-check` package. So maybe just reduce it down to a mostly-empty placeholder package.json file and a README, since I suspect most links are to the root of the package or the README.

**Pull request merged**
