### PR TITLE
docs: replace dep-check in guides

### PR DESCRIPTION
**Pull request by tido64**
### Description

Update guides to use `align-deps`.

### Test plan

```
cd docsite
yarn
yarn start
```

Verify:

- http://localhost:3000/rnx-kit/docs/introduction
- http://localhost:3000/rnx-kit/docs/dependencies
- http://localhost:3000/rnx-kit/docs/guides/getting-started
- http://localhost:3000/rnx-kit/docs/guides/dependency-management

### CODE REVIEW

**Comment by kelset** [comment]
I think we want to wait for this until we are ready for the full 2.0 rollout

**Comment by tido64** [comment]
> I think we want to wait for this until we are ready for the full 2.0 rollout

Yup, it's listed under "post-release" in https://github.com/microsoft/rnx-kit/issues/1890

**Review by afoxman — APPROVED** [review]
Looks good to me, thanks for updating the guides!

Is there a place for --vigilant anywhere in the guides? I can't recall if you retired that flag or not, but I remember some "vigilant" code in the recent rounds of PRs for align-deps.

**Comment by tido64** [comment]
> Looks good to me, thanks for updating the guides!
> 
> Is there a place for --vigilant anywhere in the guides? I can't recall if you retired that flag or not, but I remember some "vigilant" code in the recent rounds of PRs for align-deps.

The only instances I can find after this change is in the [Dependency Management](https://microsoft.github.io/rnx-kit/docs/architecture/dependency-management#zero-config). But we've added notes there instead since it's the original dep-check RFC.

**Pull request merged**
