### PR TITLE
fix(align-deps): ensure react-native-screens works with New Arch

### PR DESCRIPTION
**Pull request by balazsgerlei**
### Description

`react-native-screens` [3.28.0](https://github.com/software-mansion/react-native-screens/releases/tag/3.28.0) broke compatibility with 0.72 + New Arch. See also [discussion ](https://github.com/software-mansion/react-native-screens/issues/1985#issuecomment-1875344124) for more evidence.

### Test plan

n/a

### CODE REVIEW

**Comment by balazsgerlei** [comment]
@microsoft-github-policy-service agree

**Review by tido64 — APPROVED** [review]
Thanks for this! Can you also run `yarn change` to and push a change log? This ensures that a new version will get published in the next round.

**Comment by balazsgerlei** [comment]
Sure, I've committed the changeset - hope I did it right as this is my first contribution to this repo! So exciting. 🤩

**Comment by tido64** [comment]
Thanks again! Have a nice weekend 😊

**Comment by balazsgerlei** [comment]
Have a nice weekend too!

**Pull request merged**
